{% set name = "compaction" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 38693d689332c69b6d67739631bd977e42c25a9fea01320725feb313ec7a643e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - compact = compaction.cli:compact

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - click
    - landlab
    - numpy
    - pandas
    - pyyaml
    - scipy

test:
  requires:
    - pytest
    - pytest-benchmark
    - pytest-datadir
    - pytest-mypy
  imports:
    - compaction
  commands:
    - compact --help
    - compact show --help
    - compact setup --help
    - compact run --help
    - mkdir example && compact run $(compact setup example)
    - pytest --mypy --pyargs compaction --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: http://github.com/mcflugen/compaction
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compact columns of sediment
  description: |
    Sediment compaction and corresponding porosity variations are modeled
    by a simple exponential with depth. The porosity solution is derived
    analytically as a complicated function of pore water pressure, but the
    underlying form is shown to approximate an exponential except near the
    surface where the behavior is linear.
  doc_url: http://compaction.readthedocs.io
  dev_url: http://github.com/mcflugen/compaction

extra:
  recipe-maintainers:
    - mcflugen
