{% set version = "0.2.0" %}

package:
  name: compaction
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/compaction/compaction-{{ version }}.tar.gz
  sha256: b9cf6b28ef77ff5c072dcb752959728487754ccdede53705ec85130819eaaed9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - compact = compaction.cli:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - click
    - landlab
    - numpy
    - pandas
    - pyyaml
    - scipy

test:
  commands:
    - compact --help
    - compact --version
  imports:
    - compaction

about:
  home: http://github.com/mcflugen/compaction
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Compact columns of sediment"
  description: |
    Sediment compaction and corresponding porosity variations are modeled
    by a simple exponential with depth. The porosity solution is derived
    analytically as a complicated function of pore water pressure, but the
    underlying form is shown to approximate an exponential except near the
    surface where the behavior is linear.
  doc_url: http://compaction.readthedocs.io
  dev_url: http://github.com/mcflugen/compaction

extra:
  recipe-maintainers:
    - mcflugen
