travis:
  secure:
    BINSTAR_TOKEN: IHLQyiFD4hvKR62kWgozQ+EEbFp9rZZvFGJgSNtAl7J0WeTJfSzJ2tdPNAljxwO2QuLMlztl/1lcp75gEKyUq+7EOS0uWg/J03vCDVyTS+qe1yMhXqq6ZAj9+dqwpVdtcLNT48cRNOipZDIRbpwkViQ0hOCAbZOK2GYCkMK75EPhm3O/D51UlYbK01ZX3UDD7BY4nESX1b9tLerDCqVo+gIY5GZ+mhXj2vhVPrLTbnoU9+cboOX3Ge1+jANvK7pRC7Ue9SmfDTDwqpy6kqx/HcU8sOEGrjFDT/cbn57XbFsAUN+GhykO2990GWvZZdZyHMiAVcoLS+k0KrcW3AJZCCQpRhcTXayb1wPEKuxGUlecPJc+0ikrOpsZwWTSpECqNzVBMJG9atYm5JJTxxxdN3t9WzeUxNXkofgmdioveeDg3gxFawR+WPa3ap6bTYwsrs5W171Xu6olzXruVNxZbPiHR395037TMld2GhbIDG+dAE5M5eYVG8aCYCMJ2tu2Xz8OkW1eSJWOPMsDMCWzkjiOJNYpY/G9izuktPHVNbrOkimHn5t4tg6ANKy8dhhFShCLFVGph55bT53/sw8VnKTVNrMeQOdl0O5NuPi+5RsxSoyrbQcLu/2K1sYsvzLFUVLsnF0Jocv9tX74qrOsdxYQyjQToSPF2bRBXKyjYAc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
