travis:
  secure:
    BINSTAR_TOKEN: ha2WL6sPSQsRecgRPIvogEuhGb7wWU6mg0pB+/een/niCpn9ZvC4UquHhtdjhMcIuwWCp4/iYWBOb4GJoFNeW1UMssIgn+Zqk8IIgTg8wggHw8vm/LYJopYbi1ekkFeZ1vP8Wc/cZQCcLN9KxgCeAoVnLRVJ74mXv+mNKgbp5dgJaLNo9XXOTGLegWBYoGmjPCjFzfkqhN2XrE+tj9GVM0c1p4ggiPWtC75EaAt/nj2gQznqgXV8FYj3yeX1NQmgxPjfpvTaShGRnZdlpBf4kG8bUz/zqrMn22FusQhcI3gcPJsHJgvA3BBi4J5d0lQCykOUGYCKGCoD3Pt1+rf8yhJRm/qzI4V/eAeJiRyX3oVT6Tt7AYJKTj8sqg0lHupz64iA+zPxTVw9XZEAAuaD7QRDrQnmJs7+uE+1IXaW005M3e6Zm5BPKTbi5YJ6U5YCWUJMVGxftaPUCpLuzQ04ipKuLSLI7LeFuD91pKYj3Wvx0ZvMobt9cLFkFjiWJQDY3mugEg4fl6HuM/xRBFGmY6K2iuSHzsPWHxS/DXXvpfvmCRz1j19hoPVlX/P74r7+hZazhuLPfNR511Vplxd8GoF0qQzNcfg8IBWiRNmntXQ/v7sIFm/AN2qhkAxa1Myiyob3IKZqpXMZkG5dXyzg3as6Rer2rjA6EYYwSSk3sUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
